export const BannerData = [
  {
    id: 1,
    title: 'Energize Society',
    titleTwo: 'Reliables',
    titleThree: 'Energy',
    subtitle: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit.',
    subtitleTwo: 'iste sunt. Voluptatem, provident commodi.',
    linkOne: '/',
    linkTwo: '/',
    linkOneLabel: 'Learn More About',
    linkTwoLabel: 'Our Services',
    imageSrc: '/images/bannerimg2.jpg',
    imageAlt: 'banner',
  },
  {
    id: 2,
    title: 'we find highest use',
    titleTwo: 'for all',
    titleThree: 'resources',
    subtitle: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit.',
    subtitleTwo: 'iste sunt. Voluptatem, provident commodi.',
    linkOne: '/',
    linkTwo: '/',
    linkOneLabel: 'Learn More About',
    linkTwoLabel: 'Our Services',
    imageSrc: '/images/bannerimg1.jpg',
    imageAlt: 'banner',
  },
];
